//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.10 at 08:17:48 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ercot.com/schema/2007-06/nodal/ews/message", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ercot.schema._2007_06.nodal.ews.message;
